amqp:
  host: ${AMQP_HOST}
  port: ${AMQP_PORT}
  username: ${AMQP_USERNAME}
  password: ${AMQP_PASSWORD}

mysql:
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none